image: python:3.8.6-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - remote
    - restoredb

remote_routines:
  stage: remote
  before_script:
    - echo -e "${ID_RSA_CONTENT//_/\\n}" > /id_rsa
    - "chmod 600 /id_rsa"
    - python -V  # Print out python version for debugging
    - python -m venv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt
    - python remotedb.py ${GITLAB_USER_LOGIN}
    - python remotehost.py
    - ls
  artifacts:
    paths: 
      - ./sapiencia*
    expire_in: 30min  
  only:
    - master
  except:
    - tags

pg_restore:
  stage: restoredb
  depends_on:
    - remote_routines
  before_script:
    - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - apt-get update && apt-get install -y postgresql-12
    - python -m venv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt
    - python pg_restore.py
  only:
    - master
  except:
    - tags  