image: python:3.8.6-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - remote

remote_routines:
  stage: remote
  before_script:
    - apt update && apt install -y gettext-base
    - echo -e "${ID_RSA_CONTENT//_/\\n}" > /id_rsa
    - "chmod 600 /id_rsa"
    - python -V  # Print out python version for debugging
    - python -m venv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt # you can also use tox
    - envsubst < config.ini
    - python remotedb.py ${GITLAB_USER_LOGIN}
    - python remotehost.py
  only:
    - master
