image: python:3.8.6-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - remote
    - restoredb

remote_routines:
  stage: remote
  before_script:
    - echo -e "${ID_RSA_CONTENT//_/\\n}" > /id_rsa
    - "chmod 600 /id_rsa"
    - python -V  # Print out python version for debugging
    - python -m venv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt
    - python remotedb.py ${GITLAB_USER_LOGIN}
    - python remotehost.py
  artifacts:
    paths: 
      - ./sapiencia*
      - ./database.ini
    expire_in: 30min  
  only:
    - master
  except:
    - tags

pg_restore:
  stage: restoredb
  dependencies:
    - remote_routines
  before_script:
    - apt-get update --quiet && apt-get install -y --quiet wget gnupg2 gnupg
    - echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    - apt-get update --quiet && apt-get install -y --quiet postgresql-client-12 #postgresql-12
    - python -m venv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt
    - python pg_restore.py
  artifacts:
    paths:
      - ./database.ini
  only:
    - master
  except:
    - tags  