image: python:3.8.6-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - build
    - remote_operation
    - restore

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

prepare_env:
  stage: remote_operation
  script:
    - pip install -r requirements.txt # you can also use tox
  only:
    - master

remotedb:
  stage: remote_operation
  before_script:
    - apt update && apt install -y gettext-base
    - echo -e "${ID_RSA_CONTENT//_/\\n}" > /id_rsa
    - "chmod 600 /id_rsa"
  script:
    - envsubst < config.ini
    - python remotedb.py ${GITLAB_USER_LOGIN}
    - python remotehost.py
  artifacts:
    paths:
      - remotedbs/*
  only:
    - master



